apiVersion: gateway.api-platform.wso2.com/v1alpha1
kind: LlmProviderTemplate
metadata:
  name: demo-llm-template-apim
  namespace: apigateway-demo-apim
  labels:
    gateway.api-platform.wso2.com/restapi-target: wso2-crd-apim
spec:
  displayName: demo-llm-template-apim
  promptTokens:
    identifier: usage.prompt_tokens
    location: payload
  completionTokens:
    identifier: usage.completion_tokens
    location: payload
  totalTokens:
    identifier: usage.total_tokens
    location: payload
---
apiVersion: gateway.api-platform.wso2.com/v1alpha1
kind: LlmProvider
metadata:
  name: demo-llm-provider-apim
  namespace: apigateway-demo-apim
  labels:
    gateway.api-platform.wso2.com/restapi-target: wso2-crd-apim
spec:
  displayName: demo-llm-provider-apim
  version: v1.0
  template: demo-llm-template-apim
  accessControl:
    mode: allow_all
  upstream:
    url: https://example-llm-upstream.invalid
    auth:
      type: api-key
      header: Authorization
      value:
        valueFrom:
          secretKeyRef:
            name: demo-management-secrets-apim
            key: provider-token
---
apiVersion: gateway.api-platform.wso2.com/v1alpha1
kind: LlmProxy
metadata:
  name: demo-llm-proxy-apim
  namespace: apigateway-demo-apim
  labels:
    gateway.api-platform.wso2.com/restapi-target: wso2-crd-apim
spec:
  displayName: demo-llm-proxy-apim
  version: v1.0
  provider:
    id: demo-llm-provider-apim
